import type { ForwardRefExoticComponent, ReactNode, RefAttributes } from 'react'
import type { IconName } from '../types/icon-name'
import {
  History,
  ScrollText,
  Menu,
  FlipVertical,
  Sparkles,
  Clock3,
  Lock,
  SquarePen,
  CircleUserRound,
  Columns3,
  EthernetPort,
  LogOut,
  SquareCheckBig,
  NotebookTabs,
  ChevronDown,
  CalendarDays,
  Clock9Icon,
  Plus,
  Trash,
  Eye,
  Activity,
  Users,
  Minus,
  CreditCard,
  Mail,
  Briefcase,
  Building,
  type LucideProps,
  Clock,
  Album,
  Upload,
  Calendar,
  Hourglass,
  File,
  FileClock,
  Check,
  AlertCircle,
  LayoutDashboard,
} from 'lucide-react'

export const ICONS: Record<
  IconName,
  ForwardRefExoticComponent<Omit<LucideProps, 'ref'> & RefAttributes<SVGSVGElement>>
> = {
  users: Users,
  activity: Activity,
  trash: Trash,
  alert: AlertCircle,
  eye: Eye,
  plus: Plus,
  menu: Menu,
  star: Sparkles,
  check: Check,
  minus: Minus,
  history: History,
  adjustment: Columns3,
  collaborator: CircleUserRound,
  cpf: CreditCard,
  sector: Building,
  email: Mail,
  calendar: Calendar,
  role: Briefcase,
  report: ScrollText,
  logout: LogOut,
  clock: Clock3,
  lock: Lock,
  edit: SquarePen,
  workload: Clock9Icon,
  confirm: SquareCheckBig,
  timer: Clock,
  album: Album,
  upload: Upload,
  hourglass: Hourglass,
  file: File,
  dashboard: LayoutDashboard,
  'justication-type': EthernetPort,
  'week-schedule': NotebookTabs,
  'arrow-down': ChevronDown,
  'time-card': FlipVertical,
  'day-off-schedule': CalendarDays,
  'file-clock': FileClock,
}
