import type { ForwardRefExoticComponent, ReactNode, RefAttributes } from 'react'
import type { IconName } from '../types/icon-name'
import {
  History,
  ScrollText,
  Menu,
  FlipVertical,
  Sparkles,
  Clock3,
  Lock,
  SquarePen,
  CircleUserRound,
  LogOut,
  SquareCheckBig,
  NotebookTabs,
  ChevronDown,
  CalendarDays,
  Clock9Icon,
  Plus,
  Trash,
  Eye,
  Activity,
  Users,
  CreditCard,
  Mail,
  Briefcase,
  Building,
  type LucideProps,
} from 'lucide-react'

export const ICONS: Record<
  IconName,
  ForwardRefExoticComponent<Omit<LucideProps, 'ref'> & RefAttributes<SVGSVGElement>>
> = {
  users: Users,
  activity: Activity,
  trash: Trash,
  eye: Eye,
  plus: Plus,
  menu: Menu,
  star: Sparkles,
  history: History,
  collaborator: CircleUserRound,
  cpf: CreditCard,
  sector: Building,
  email: Mail,
  role: Briefcase,
  report: ScrollText,
  logout: LogOut,
  clock: Clock3,
  lock: Lock,
  edit: SquarePen,
  workload: Clock9Icon,
  confirm: SquareCheckBig,
  'week-schedule': NotebookTabs,
  'arrow-down': ChevronDown,
  'time-card': FlipVertical,
  'day-off-schedule': CalendarDays,
}
